# main text of home
title: Alvin Cris Tabontabon
bio: An Asian man who codes to eat noodles
description: An Asian man who codes to eat noodles

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: auto

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

url: https://acltabontabon.com
permalink: /:title/
analytics-google: 'G-B501PMT6GE'

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: acltabontabon # enter this from your disqus account
  categories: [blog] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: acltabontabon
twitter: acltabontabon
#instagram: myinstagram
linkedin: acltabontabon
github: acltabontabon
email: me@acltabontabon.com

authors:
  actabontabon:
    name: Alvin Cris Tabontabon
    bio: An Asian man who codes to eat noodles
    external-image: false
    picture: assets/images/profile.jpg
    twitter: acltabontabon

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

projects: true
about: true
blog: true

# Posts config
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
